version: "3"
services:
  nexus-dev:
    image: node:18
    container_name: nexus-dev
    build:
      context: ./nexus-dev
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    networks:
      - webgateway

networks:
  webgateway:
    driver: bridge
