version: "3"
services:
  nexus-dev:
    image: node:18
    container_name: nexus-dev
    build:
      context: ./nexus-dev
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    networks:
      - webgateway

  nexus-dev-bo:
    image: node:17
    container_name: nexus-dev-bo
    build:
      context: ./nexus-dev-bo
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - webgateway

  nexus-user:
    image: node:16
    container_name: nexus-user
    build:
      context: ./nexus-user
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3003:3003"
    networks:
      - webgateway

  nexus-user-bo:
    image: node:15
    container_name: nexus-user-bo
    build:
      context: ./nexus-user-bo
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    networks:
      - webgateway

networks:
  webgateway:
    driver: bridge
